


- name: Print env variable
  shell: echo $PATH
  register: print_result

- name: print message
  debug:
    msg: "{{ print_result.stdout_lines }}" # to expose it from the ansible command line so that it is visible to us 